name: ci
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install web
        run: cd apps/web && npm ci
      - name: Typecheck web
        run: cd apps/web && npx tsc --noEmit
      - name: Install api
        run: cd apps/api && npm ci
      - name: Typecheck api
        run: cd apps/api && npx tsc --noEmit
